name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Replace with your Terraform version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Print Environment Variables
        run: printenv | grep TF_API_TOKEN
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Initialize Terraform
        run: terraform init
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Validate Terraform Configuration
        run: terraform validate
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Plan Terraform Changes
        run: terraform plan -out=tfplan
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Apply Terraform Changes
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
